# Copyright (c) 2021 Tailscale Inc & AUTHORS All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
name: 'Connect Tailscale'
description: 'Connect your GitHub Action workflow to Tailscale'
branding:
  icon: 'arrow-right-circle'
  color: 'gray-dark'
inputs:
  version:
    description: 'Tailscale version to use.'
    required: true
    default: '1.36.0'
  tailscaled_args:
    description: 'Optional additional arguments to `tailscaled`'
    required: false
    default: ''
  tailscale_args:
    description: 'Optional additional arguments to `tailscale up`'
    required: false
    default: ''
  hostname:
    description: 'Fixed hostname to use.'
    required: false
    default: ''
  oauth_client_id:
    description: 'Tailscale OAuth Client ID.'
    required: true
    default: ''
  oauth_client_secret:
    description: 'Tailscale OAuth Client Secret.'
    required: true
    default: ''
runs:
    using: 'composite'
    steps:
      - name: Check Runner OS
        if: ${{ runner.os != 'Linux' }}
        shell: bash
        run: |
          echo "::error title=⛔ error hint::Support Linux Only"
          exit 1
      - name: Download Tailscale
        shell: bash
        id: download
        env:
          VERSION: ${{ inputs.version }}
        run: |
          MINOR=$(echo "$VERSION" | awk -F '.' {'print $2'})
          if [ $((MINOR % 2)) -eq 0 ]; then
            URL="https://pkgs.tailscale.com/stable/tailscale_${VERSION}_amd64.tgz"
          else
            URL="https://pkgs.tailscale.com/unstable/tailscale_${VERSION}_amd64.tgz"
          fi
          curl "$URL" -o tailscale.tgz
          tar -C /tmp -xzf tailscale.tgz
          rm tailscale.tgz
          TSPATH=/tmp/tailscale_${VERSION}_amd64
          sudo mv "${TSPATH}/tailscale" "${TSPATH}/tailscaled" /usr/bin
      - name: Run Tailscale
        shell: bash
        env:
          TAILSCALED_ADDITIONAL_ARGS: ${{ inputs.tailscaled_args }}
          TAILSCALE_ADDITIONAL_ARGS: ${{ inputs.tailscale_args }}
          HOSTNAME: ${{ inputs.hostname }}
          OAUTH_CLIENT_ID: ${{ inputs.oauth_client_id }}
          OAUTH_CLIENT_SECRET: ${{ inputs.oauth_client_secret }}
        run: |
          ACCESS_TOKEN=$(curl -d "client_id=${OAUTH_CLIENT_ID}" -d "client_secret=${OAUTH_CLIENT_SECRET}" \
               "https://api.tailscale.com/api/v2/oauth/token" | jq -r '.access_token')
          AUTH_TOKEN=$(curl "https://api.tailscale.com/api/v2/tailnet/rollkall.com/keys" \
              -u "$ACCESS_TOKEN:$OAUTH_CLIENT_SECRET" \
              --data-binary '
              {
                  "capabilities": {
                      "devices": {
                          "create": {
                              "reusable": false,
                              "ephemeral": true,
                              "preauthorized": true,
                              "tags": [ "tag:ci-runner" ]
                          }
                      }
                  },
                  "expirySeconds": 1800
              }' | jq -r '.key'
          )
          sudo tailscaled \
            ${TAILSCALED_ADDITIONAL_ARGS} 2>~/tailscaled.log &
          if [ -z "${HOSTNAME}" ]; then
            HOSTNAME="github-$(cat /etc/hostname)"
          fi
          sudo tailscale up --authkey ${AUTH_TOKEN} --hostname=${HOSTNAME} --accept-routes ${TAILSCALE_ADDITIONAL_ARGS} --accept-dns
